### ISSUE TITLE
EVALUACIÓN Y OBSERVACIONES DE LA PRÁCTICA #3

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/practicaprototipos-equipo-ybjs#3]
EVALUACIÓN Y OBSERVACIONES DE LA PRÁCTICA 3

**Comment by IsaHuerta23** [comment]
Primera observación:
- No contiene las 20 figuras/ilustraciones.

**Comment by Band-hi** [comment]
Observación:
No se describen resultados obtenidos, solamente la conclusión.

**Comment by Rigoberto2001** [comment]
OBSERVACIÓN DE LA PRACTICA 3: El contenido de la información se encuentra en la misma hoja del índice. De igual manera no se respeta un tamaño único de las ilustraciones.

**Comment by IsaHuerta23** [comment]
EVALUACIÓN DE LA PRÁCTICA #3:

[Rubrica 3 Practica 3.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipo-ybjs/files/6166533/Rubrica.3.Practica.3.pdf)

**Comment by IsaHuerta23** [comment]
Calificación de la Práctica 3: 19/20

**Comment by Yabin-2021** [comment]
[Reporte de Práctica - GUI Calculadora.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipo-ybjs/files/6191212/Reporte.de.Practica.-.GUI.Calculadora.pdf)
Anexo Reporte de Práctica 3 - Calculadora

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by Yabin-2021** [comment]
[Reporte de Práctica - GUI Calculadora.pdf](https://github.com/SistemasTecTlaxiaco/practicaprototipos-equipo-ybjs/files/6191313/Reporte.de.Practica.-.GUI.Calculadora.pdf)
Anexo Reporte de Práctica 3. (Agregando a la compañera Sandra)
